/**
 * Sprite-sheet overlays for BLACK MARKET.
 *
 * Sheets are generated by `tools/animation/generate_atlas.mjs` into
 * assets/animations/<name>.webp + <name>.json (TexturePacker-compatible).
 * PixiJS v8 auto-detects the spritesheet JSON (meta.image + frames) via
 * Assets.load and returns a Spritesheet with named frame arrays.
 *
 * Anything that fails to load degrades silently (empty frames -> no overlay),
 * so placeholder/animated sheets are optional at runtime.
 */
import { AnimatedSprite, Assets, Container, Spritesheet, Texture } from 'pixi.js';

/** Uniform authored frame duration (140ms) for every generated sheet. */
const FRAME_MS_PER_TICK = 1 / (0.14 * 60);

export class OverlayAtlas {
  private readonly sheets = new Map<string, Spritesheet>();

  async load(...names: string[]) {
    await Promise.all(
      names.map(async (name) => {
        try {
          const sheet = await Assets.load<Spritesheet>(`./animations/${name}.json`);
          if (sheet && (sheet.animations || sheet.textures)) {
            this.sheets.set(name, sheet);
          }
        } catch {
          /* sheet absent/malformed — overlay will be a no-op */
        }
      }),
    );
  }

  /** Play a named sheet once at a position in host space. */
  play(x: number, y: number, name: string, scale = 1, host: Container, loop = false) {
    const sheet = this.sheets.get(name);
    const frames: Texture[] = sheet?.animations?.default ?? Object.values(sheet?.textures ?? {});
    if (!frames.length) return;
    const anim = new AnimatedSprite(frames, false);
    anim.anchor.set(0.5);
    anim.position.set(x, y);
    anim.scale.set(scale);
    anim.animationSpeed = FRAME_MS_PER_TICK;
    anim.loop = loop;
    anim.onComplete = () => {
      if (anim.parent) anim.parent.removeChild(anim);
      anim.destroy();
    };
    host.addChild(anim);
    anim.gotoAndPlay(0);
  }
}